name: Deploy Practice Theme

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & Build
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies and build
        working-directory: wp-content/themes/practice-theme
        run: |
          npm ci
          npm run build

      - name: Deploy theme via SSH with password
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
          # Test connection
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'Connection successful'"
          
          # Create directory
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "mkdir -p domains/palegoldenrod-mink-986148.hostingersite.com/public_html/wp-content/themes/practice-theme"
          
          # Deploy files
          tar czf - -C wp-content/themes/practice-theme . | \
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "tar xzf - -C domains/palegoldenrod-mink-986148.hostingersite.com/public_html/wp-content/themes/practice-theme/"

      - name: Update WordPress URLs in wp-config.php
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "cd domains/palegoldenrod-mink-986148.hostingersite.com/public_html && \
             grep -q \"WP_HOME\" wp-config.php || sed -i \"/That's all, stop editing!/i define('WP_HOME','https://paleqoldenrod-mink-986148.hostingersite.com');\" wp-config.php && \
             grep -q \"WP_SITEURL\" wp-config.php || sed -i \"/That's all, stop editing!/i define('WP_SITEURL','https://paleqoldenrod-mink-986148.hostingersite.com');\" wp-config.php"

      - name: Update WordPress database URLs
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "cd domains/palegoldenrod-mink-986148.hostingersite.com/public_html && \
             mysql -h localhost -u u529539146_space -p'Yoniyoni1509!' u529539146_space -e \"UPDATE wp_options SET option_value = 'https://paleqoldenrod-mink-986148.hostingersite.com' WHERE option_name = 'home';\" && \
             mysql -h localhost -u u529539146_space -p'Yoniyoni1509!' u529539146_space -e \"UPDATE wp_options SET option_value = 'https://paleqoldenrod-mink-986148.hostingersite.com' WHERE option_name = 'siteurl';\""

      - name: Verify deployment
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Check if theme files exist
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "ls -la domains/palegoldenrod-mink-986148.hostingersite.com/public_html/wp-content/themes/practice-theme/"
          
          # Check for CSS files
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "find domains/palegoldenrod-mink-986148.hostingersite.com/public_html/wp-content/themes/practice-theme/ -name '*.css' -type f"