name: Deploy Practice Theme

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & Build
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies and build
        working-directory: wp-content/themes/practice-theme
        run: |
          npm ci
          npm run build

      - name: Deploy theme via SSH with password
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
          # Test connection
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'Connection successful'"
          
          # Create directory for the new site
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "mkdir -p domains/darkgoldenrod-whale-502822.hostingersite.com/public_html/wp-content/themes/practice-theme"
          
          # Deploy files
          tar czf - -C wp-content/themes/practice-theme . | \
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "tar xzf - -C domains/darkgoldenrod-whale-502822.hostingersite.com/public_html/wp-content/themes/practice-theme/"
          
          # Set correct permissions
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            "find domains/darkgoldenrod-whale-502822.hostingersite.com/public_html/wp-content/themes/practice-theme -type f -exec chmod 644 {} \; && \
             find domains/darkgoldenrod-whale-502822.hostingersite.com/public_html/wp-content/themes/practice-theme -type d -exec chmod 755 {} \;"